CREATE TABLE BUILDING(
    ID          VARCHAR2(50),
    NAME        VARCHAR2(50) NOT NULL,
    VERTEX_NUM  NUMBER NOT NULL,
    AREA        SDO_GEOMETRY NOT NULL,
    CONSTRAINT "BUILDING_ID" PRIMARY KEY ("ID") 
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
    VALUES (
    'BUILDING',
    'AREA',
    SDO_DIM_ARRAY(
      SDO_DIM_ELEMENT('X', 0, 580, 1),
      SDO_DIM_ELEMENT('Y', 0, 820, 1)
       ),
    NULL
);

CREATE INDEX BUILDING_AREA ON BUILDING(AREA)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE TABLE STUDENT(
    ID          VARCHAR2(50),
    POSITION    SDO_GEOMETRY NOT NULL,
    CONSTRAINT "STUDENT_ID" PRIMARY KEY ("ID")
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
    VALUES (
    'STUDENT',
    'POSITION',
    SDO_DIM_ARRAY(
      SDO_DIM_ELEMENT('X', 0, 580, 1),
      SDO_DIM_ELEMENT('Y', 0, 820, 1)
       ),
    NULL
);

CREATE INDEX STUDENT_POS ON STUDENT(POSITION)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE TABLE ANNOUNCE_SYS(
    ID          VARCHAR2(50),
    RADIUS      NUMBER,
    CENTER      SDO_GEOMETRY NOT NULL,
    AREA        SDO_GEOMETRY NOT NULL,
    CONSTRAINT "ANNOUNCE_SYS_ID" PRIMARY KEY ("ID")
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
    VALUES (
    'ANNOUNCE_SYS',
    'CENTER',
    SDO_DIM_ARRAY(
      SDO_DIM_ELEMENT('X', 0, 580, 1),
      SDO_DIM_ELEMENT('Y', 0, 820, 1)
       ),
    NULL
);

INSERT INTO USER_SDO_GEOM_METADATA
    (TABLE_NAME,
     COLUMN_NAME,
     DIMINFO,
     SRID)
    VALUES (
    'ANNOUNCE_SYS',
    'AREA',
    SDO_DIM_ARRAY(
      SDO_DIM_ELEMENT('X', 0, 580, 1),
      SDO_DIM_ELEMENT('Y', 0, 820, 1)
       ),
    NULL
);

CREATE INDEX ANNOUNCE_SYS_CENTER ON ANNOUNCE_SYS(CENTER)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX ANNOUNCE_SYS_AREA ON ANNOUNCE_SYS(AREA)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

COMMIT;